project: cn-north-7
yuming: https://cse.${project}.myhuaweicloud.com #https://cse.c-fr-1.c.external.com  #https://cse.cn-north-7.myhuaweicloud.com:443 #https://cse.cn-east-2.myhuaweicloud.com:443 #https://cse.cn-north-1.myhuaweicloud.com:443
consumer: 100.95.149.241:30100,https://100.95.154.195
PhysicalMultiTenant: 100.85.219.255
localcse: 127.0.0.1
endpointType: publicEndpoint
accessEnv: ulanchabu3
engineName: lhy-nodelete
port: 1112

APPLICATION_ID: dtm
service_description:
  name: bank-a
  version: 1.0.1
  properties: {
    server: D,
    handle: AutoHandle
  }
  environment: development

servicecomb:
  monitor:
    client:
      enable: false
  release_way: canary  #新版本灰度开关
  #  engine:
  #  name: cse-iswfit-lhy-nodelete
  service:
    registry:
      #address: https://${PhysicalMultiTenant}:30100    #物理多租
      address: http://${cse_ip}:30100                 #本地中心
      #      address: https://192.168.239.137:30100,https://192.168.239.228:30100   #消费者云
      #      address: ${yuming}  #HC
      instance:
        watch: false
        pull:
          interval: 1
    registry-serverB:
      address: https://${PhysicalMultiTenant}:30100
      instance:
        watch: false
        pull:
          interval: 1
#  config:
#    ignoreResolveFailure: true
#    client:
#      serverUri: https://${PhysicalMultiTenant}:30103 #物理多租
#      #      serverUri: http://${localcse}:30113                 #本地中心
#      #      serverUri: https://192.168.239.137:30103,https://192.168.239.228:30103  #消费者云
#      #      serverUri: ${yuming}  #HC
#      refreshPort: 30104
#      refreshMode: 1
#      refresh_interval: 1000
  #cse:
  rest:
    address: 0.0.0.0:${port} #"[::]:1111?sslEnabled=false"
  #    parameter:
  #      query:
  #        emptyAsNull: true

  handler:
    chain:
      Consumer:
        default: loadbalance,bizkeeper-consumer,dtm-consumer
      Provider:
        default: dtm-provider
  tracing:
    collector:
      address: http://100.85.218.101:9411

  fallback:
    Consumer:
      enabled: false
  credentials:
    accessKey: BAKFCVRZUZCOEERYM2O9
    secretKey: ah64LPdAycXH74JdOpsIjZLGKUqLDUsH1EwctE3i
    project: ${project}
    akskCustomCipher: default

  #servicecomb:
  accesslog:
    enabled: true  #启用access log
    pattern: "%h - - %t %r %s %B %{key1}SCB-ctx %m %s %T %D %v %p %r %q %H"  # %r %s %B %{key1}SCB-ctx %m %s %T %D %v %p %r %q %H

ssl.engine: openssl
ssl.protocols: TLSv1.2
ssl.ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA
#ssl.rest.consumer.authPeer: false
ssl.authPeer: false
ssl.checkCN.host: false
####################certificates config
ssl.trustStore: trust.jks
ssl.trustStoreType: JKS
ssl.trustStoreValue: Test1234_
ssl.keyStore: server.p12
ssl.keyStoreType: PKCS12
ssl.keyStoreValue: Test1234_
ssl.crl: revoke.crl
ssl.sslCustomClass: com.huawei.cse.common.SSLCustomServer

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    banka:
      username: ${db_user_name}
      password: ${db_user_pwd}
      url: jdbc:mysql://${db_ip}:3306/banka?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver